server.port=8080
spring.application.name=gateway-service

jwt.secret=${JWT_SECRET}
# Activation de la découverte des routes via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Définition des routes explicites pour l'API du user-service
spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**

# Configuration du client Eureka de la Gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# On applique la sécurité et le Circuit Breaker sur cette route !
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.name=userServiceCircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/fallback/user-service

spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=10000

# --- Configuration Resilience4J ---
# Si un appel prend plus de 2 secondes (2000ms), le circuit breaker coupe l'appel et bascule sur le fallback
resilience4j.timelimiter.instances.userServiceCircuitBreaker.timeout-duration=2s