server.port=8080
spring.application.name=gateway-service

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
jwt.secret=${JWT_SECRET}
# Activation de la découverte des routes via Eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Définition des routes explicites pour l'API du user-service
spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/users/**

# Configuration du client Eureka de la Gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# On applique la sécurité et le Circuit Breaker sur cette route !
spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter
spring.cloud.gateway.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.name=userServiceCircuitBreaker
spring.cloud.gateway.routes[0].filters[1].args.fallbackUri=forward:/fallback/user-service

# Route pour abonnement-service
spring.cloud.gateway.routes[1].id=abonnement-service-route
spring.cloud.gateway.routes[1].uri=lb://ABONNEMENT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/abonnements/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter

# Route pour plans
spring.cloud.gateway.routes[2].id=plans-route
spring.cloud.gateway.routes[2].uri=lb://ABONNEMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/plans/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter

# Route pour lead-service
spring.cloud.gateway.routes[3].id=lead-service-route
spring.cloud.gateway.routes[3].uri=lb://LEAD-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/leads/**

# Route pour commande-service
spring.cloud.gateway.routes[4].id=commande-route
spring.cloud.gateway.routes[4].uri=lb://LEAD-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/commands/**

# Route pour stock-service
# 1. STOCK-SERVICE (Boutiques)
spring.cloud.gateway.routes[5].id=boutique-service-route
spring.cloud.gateway.routes[5].uri=lb://STOCK-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/boutiques/**
spring.cloud.gateway.routes[5].filters[0]=JwtAuthenticationFilter

# 2. STOCK-SERVICE (Produits)
spring.cloud.gateway.routes[6].id=produit-service-route
spring.cloud.gateway.routes[6].uri=lb://STOCK-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/produits/**
spring.cloud.gateway.routes[6].filters[0]=JwtAuthenticationFilter

# 3. STOCK-SERVICE (Inventaires)
spring.cloud.gateway.routes[7].id=inventaire-service-route
spring.cloud.gateway.routes[7].uri=lb://STOCK-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/inventaires/**
spring.cloud.gateway.routes[7].filters[0]=JwtAuthenticationFilter

# CONFIG SERVER
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.enabled=true
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.initial-interval=2000
spring.cloud.config.retry.max-interval=10000

# --- Configuration Resilience4J ---
# Si un appel prend plus de 2 secondes (2000ms), le circuit breaker coupe l'appel et bascule sur le fallback
resilience4j.timelimiter.instances.userServiceCircuitBreaker.timeout-duration=2s