spring.application.name=user_service


server.port=8081
#server.servlet.context-path=/api

# ── Base de données PostgreSQL ──
spring.datasource.url=jdbc:postgresql://localhost:5432/erp
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ──
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# La syntaxe :${...} fournit une valeur par défaut si JWT_SECRET n'est pas défini
app.jwt.secret=${JWT_SECRET:MaCleSecreteUltraSecuriseeDeSecoursPourLeCRM2026QuiFaitPlusDe32Caracteres!}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=on_param