import { Component, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { finalize, take, timer } from 'rxjs';
import { ExternalProductResponse, IntegrationCapabilities, IntegrationEventResponse, IntegrationPlatform, IntegrationsApiService, ProductMappingResponse, ProductResponse, StockApiService, StoreConnectionResponse, StoreResponse } from '../../core/api';
import { UiFeedbackService } from '../../core/ui/ui-feedback.service';

type Panel='connect'|'mapping'|null;
@Component({selector:'app-integrations',imports:[FormsModule],templateUrl:'./integrations.component.html',styleUrl:'./business-view.scss'})
export class IntegrationsComponent implements OnInit{
 private readonly api=inject(IntegrationsApiService);private readonly stock=inject(StockApiService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);readonly feedback=inject(UiFeedbackService);
 readonly capabilities=signal<IntegrationCapabilities|null>(null);readonly connections=signal<readonly StoreConnectionResponse[]>([]);readonly stores=signal<readonly StoreResponse[]>([]);readonly products=signal<readonly ProductResponse[]>([]);readonly externalProducts=signal<readonly ExternalProductResponse[]>([]);readonly mappings=signal<readonly ProductMappingResponse[]>([]);readonly events=signal<readonly IntegrationEventResponse[]>([]);readonly selectedConnection=signal<StoreConnectionResponse|null>(null);readonly loading=signal(true);
 panel:Panel=null;busy=false;platform:IntegrationPlatform='SHOPIFY';locationChoice:'existing'|'new'='existing';connectForm={displayName:'',store:'',stockLocationId:null as number|null,newLocationName:''};externalVariantId='';internalProductId:number|null=null;
 ngOnInit():void{this.reload();this.stock.getStores().subscribe({next:v=>this.stores.set(v),error:e=>this.feedback.error(e)});this.stock.getProducts().subscribe({next:v=>this.products.set(v),error:e=>this.feedback.error(e)});this.handleProviderReturn()}
 reload():void{this.loading.set(true);let remaining=3;const done=()=>{if(--remaining===0)this.loading.set(false)};this.api.capabilities().subscribe({next:v=>{this.capabilities.set(v);done()},error:e=>{done();this.feedback.error(e)}});this.api.connections().subscribe({next:v=>{this.connections.set(v);const selected=this.selectedConnection();if(selected){const refreshed=v.find(x=>x.id===selected.id)??null;this.selectedConnection.set(refreshed);if(refreshed)this.loadMappingContext(refreshed)}done()},error:e=>{done();this.feedback.error(e)}});this.api.events().subscribe({next:v=>{this.events.set(v);done()},error:e=>{done();this.feedback.error(e)}})}
 openConnect(platform:IntegrationPlatform):void{this.platform=platform;this.panel='connect';this.locationChoice=this.stores().length?'existing':'new';this.connectForm={displayName:'',store:'',stockLocationId:this.stores()[0]?.idBoutique??null,newLocationName:''}}
 connect():void{if(!this.connectForm.displayName.trim()||!this.connectForm.store.trim())return;if(this.locationChoice==='new'){const name=this.connectForm.newLocationName.trim();if(!name)return;this.busy=true;this.stock.createStore({nomBoutique:name,plateformeType:'MANUAL'}).subscribe({next:location=>{this.stores.update(items=>[...items,location]);this.connectForm.stockLocationId=location.idBoutique;this.startAuthorization(location.idBoutique)},error:e=>{this.busy=false;this.feedback.error(e,'The fulfillment location could not be created.')}});return}if(!this.connectForm.stockLocationId)return;this.busy=true;this.startAuthorization(this.connectForm.stockLocationId)}
 private startAuthorization(stockLocationId:number):void{const request={displayName:this.connectForm.displayName.trim(),store:this.connectForm.store.trim(),stockLocationId};const operation=this.platform==='SHOPIFY'?this.api.connectShopify(request):this.api.connectWooCommerce(request);operation.pipe(finalize(()=>this.busy=false)).subscribe({next:authorization=>{globalThis.location.assign(authorization.authorizationUrl)},error:e=>this.feedback.error(e,'Store authorization could not be started.')})}
 select(connection:StoreConnectionResponse):void{this.selectedConnection.set(connection);this.panel='mapping';this.loadMappingContext(connection)}
 loadMappingContext(connection:StoreConnectionResponse):void{if(connection.status==='DISCONNECTED'){this.externalProducts.set([]);this.mappings.set([]);return}this.api.externalProducts(connection.id).subscribe({next:v=>this.externalProducts.set(v),error:e=>this.feedback.error(e,'External products could not be loaded.')});this.api.mappings(connection.id).subscribe({next:v=>this.mappings.set(v),error:e=>this.feedback.error(e)})}
 createMapping():void{const connection=this.selectedConnection();const external=this.externalProducts().find(item=>item.variantId===this.externalVariantId);if(!connection||!external||!this.internalProductId)return;this.busy=true;this.api.createMapping(connection.id,{externalProductId:external.productId,externalVariantId:external.variantId,externalSku:external.sku||undefined,externalName:external.name,internalProductId:this.internalProductId}).pipe(finalize(()=>this.busy=false)).subscribe({next:()=>{this.feedback.success('Product mapping created.');this.externalVariantId='';this.internalProductId=null;this.loadMappingContext(connection)},error:e=>this.feedback.error(e)})}
 deleteMapping(mapping:ProductMappingResponse):void{if(!confirm(`Remove mapping for ${mapping.externalName}?`))return;this.api.deleteMapping(mapping.id).subscribe({next:()=>{this.feedback.success('Product mapping removed.');const connection=this.selectedConnection();if(connection)this.loadMappingContext(connection)},error:e=>this.feedback.error(e)})}
 disconnect(connection:StoreConnectionResponse):void{if(!confirm(`Disconnect ${connection.displayName}? Revoke the app/API keys in the provider admin as well.`))return;this.api.disconnect(connection.id).subscribe({next:()=>{this.feedback.success('Store disconnected locally.');this.panel=null;this.selectedConnection.set(null);this.reload()},error:e=>this.feedback.error(e)})}
 autoImport():void{const connection=this.selectedConnection();if(!connection)return;this.busy=true;this.api.autoImport(connection.id).pipe(finalize(()=>this.busy=false)).subscribe({next:result=>{this.feedback.success(`Auto-import complete: ${result.importedCount} imported, ${result.skippedCount} skipped.`);this.loadMappingContext(connection);this.stock.getProducts().subscribe({next:v=>this.products.set(v)})},error:e=>this.feedback.error(e,'Auto-import failed.')})}
 close():void{this.panel=null;this.selectedConnection.set(null)}
 tone(status:string):string{return status==='CONNECTED'||status==='PROCESSED'?'success':status==='FAILED'||status==='ERROR'?'critical':'warning'}
 label(value:string):string{return value.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase())}
 productName(id:number):string{return this.products().find(product=>product.idProduit===id)?.nomProduit??`Product #${id}`}
 private handleProviderReturn():void{const query=this.route.snapshot.queryParamMap;const provider=query.get('provider');const connected=query.get('connected');const wooReturn=query.get('woocommerce_return')==='1';if(provider&&connected)this.feedback.success(`${this.label(provider)} authorization completed. Check webhook status and map products before importing orders.`);if(wooReturn){this.feedback.success('WooCommerce returned successfully. Waiting briefly for its server callback…');timer(1200,1800).pipe(take(3)).subscribe(()=>this.reload())}if((provider&&connected)||wooReturn)void this.router.navigate([],{relativeTo:this.route,queryParams:{provider:null,connected:null,woocommerce_return:null},queryParamsHandling:'merge',replaceUrl:true})}
}
