server.port=8888
spring.application.name=config-server

# 1. Enregistrement auprès d'Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 2. Activation du profil Vault (On vire le profil "native")
spring.profiles.active=vault

# 3. Configuration de la connexion à Vault
spring.cloud.vault.host=localhost
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http

# 4. Activation explicite du mécanisme AppRole (C'est ça qui corrige ton erreur !)
spring.cloud.vault.authentication=APPROLE
spring.cloud.vault.app-role.role-id=${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id=${VAULT_SECRET_ID}

# 5. Indiquer au Config Server d'aller chercher les configurations des microservices dans Vault
spring.cloud.config.server.vault.host=localhost
spring.cloud.config.server.vault.port=8200
spring.cloud.config.server.vault.scheme=http
spring.cloud.config.server.vault.backend=secret