name: Frontend CI Pipeline

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
    paths:
      - 'frontend_service/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/actions/build-and-scan-service/**' # Path to your reusable composite action
      - '.github/workflows/update-gitops-image.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'frontend_service/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/actions/build-and-scan-service/**'
      - '.github/workflows/update-gitops-image.yml'

jobs:
  devsecops-frontend:
    name: DevSecOps - Angular Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Reusing your existing Composite Action with project_type: 'node'
      - name: Build & Scan Frontend Service
        uses: ./.github/actions/build-and-scan-service # Path to your parameterized action file
        with:
          project_type: 'node'
          service_name: 'frontend_service'
          image_name: 'erp-frontend-service'
          run_tests: 'true'
          fail_on_vulnerabilities: 'false'
          push_image: ${{ github.event_name == 'push' }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  update-gitops:
    name: Promote frontend image to dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/feature/GitOps-setup'
    needs: devsecops-frontend
    uses: ./.github/workflows/update-gitops-image.yml
    with:
      image_name: erp-frontend-service
      image_tag: ${{ github.sha }}
    secrets:
      gitops_token: ${{ secrets.GITOPS_TOKEN }}
