name: Notification Service CI (DevSecOps)

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
    paths:
      - 'notification_service/**'
      - 'common_lib/**'
      - 'Dockerfile.microservice'
      - '.github/actions/build-and-scan-service/**'
      - '.github/workflows/notification-service-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'notification_service/**'
      - 'common_lib/**'
      - 'Dockerfile.microservice'
      - '.github/actions/build-and-scan-service/**'
      - '.github/workflows/notification-service-ci.yml'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build, scan & package notification_service
        uses: ./.github/actions/build-and-scan-service
        with:
          service_name: notification_service
          service_port: 8089
          image_name: erp-notification-service
          push_image: ${{ github.event_name == 'push' }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
