name: Stock Service CI (DevSecOps)

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
    paths:
      - 'stock_service/**'
      - 'common_lib/**'
      - 'Dockerfile.microservice'
      - '.github/actions/build-and-scan-service/**'
      - '.github/workflows/update-gitops-image.yml'
      - '.github/workflows/stock-service-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'stock_service/**'
      - 'common_lib/**'
      - 'Dockerfile.microservice'
      - '.github/actions/build-and-scan-service/**'
      - '.github/workflows/update-gitops-image.yml'
      - '.github/workflows/stock-service-ci.yml'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build, scan & package stock_service
        uses: ./.github/actions/build-and-scan-service
        with:
          service_name: stock_service
          service_port: 8084
          image_name: erp-stock-service
          push_image: ${{ github.event_name == 'push' }}
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  update-gitops:
    name: Promote stock-service image to dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/feature/GitOps-setup'
    needs: build-and-scan
    uses: ./.github/workflows/update-gitops-image.yml
    with:
      image_name: erp-stock-service
      image_tag: ${{ github.sha }}
    secrets:
      gitops_token: ${{ secrets.GITOPS_TOKEN }}
