name: User Service CI (DevSecOps)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'user_service/**' # Déclenche le pipeline SEULEMENT si ce dossier change
  pull_request:
    branches: [ main ]
    paths:
      - 'user_service/**'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Étape DevSecOps 1 : Scan du code source (SAST) avant le build
      - name: Scan des vulnérabilités du code (Trivy FS)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './user_service'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # Étape Build
      - name: Build avec Maven
        run: |
          cd user_service
          mvn clean package -DskipTests

      # Étape DevSecOps 2 : Scan de l'image Docker après le build (Container Security)
      - name: Build de l'image Docker locale
        run: |
          docker build -t erp-user-service:latest ./user_service

        # On demande à Trivy de scanner l'image
      - name: Scan de l'image Docker (Trivy Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'erp-user-service:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'