name: User Service CI (DevSecOps)

on:
  push:
    branches: [ "main", "develop", "feature/identity-auth", "feature/vault-gateway" ]
    paths:
      - 'user_service/**'
      - 'common_lib/**'
      - 'Dockerfile.microservice'
      - '.github/actions/build-and-scan-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'user_service/**'
      - 'common_lib/**'
      - 'Dockerfile.microservice'
      - '.github/actions/build-and-scan-service/**'

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build, scan & package user_service
        uses: ./.github/actions/build-and-scan-service
        with:
          service_name: user_service
          service_port: 8081
          image_name: erp-user-service